image:
  file: .gitpod.dockerfile
ports:
  - port: 3005
  - port: 6080
    onOpen: ignore
  - port: 5900
    onOpen: ignore
tasks:
  - init: yarn
    command: >
      jwm &
      yarn --cwd examples/browser start ../..
github:
  prebuilds:
    pullRequestsFromForks: true
